version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      # Монтируем весь проект в /app для доступа к скриптам и документам
      - ./:/app
      - chat_db:/data          # SQLite volume
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - QDRANT_HOST=qdrant
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on: [redis, qdrant, minio]

  redis:
    image: redis:7

  qdrant:
    image: qdrant/qdrant
    ports: ["6333:6333"]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports: ["9000:9000", "9001:9001"]
volumes:
  chat_db:
