name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest

    services:             # контейнеры, нужные для pytest
      redis:
        image: redis:7
        ports: ['6379:6379']
      qdrant:
        image: qdrant/qdrant
        ports: ['6333:6333']
      minio:
        image: minio/minio
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        ports: ['9000:9000', '9001:9001']

    steps:
      - uses: actions/checkout@v3

      # ---------- Backend : тесты ----------
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install backend deps
        run: pip install -r backend/requirements.txt --quiet

      - name: Run pytest
        run: pytest -q               # теперь тесты должны проходить!

      # ---------- Docker build ----------
      - name: Build backend image
        run: docker build -f backend/Dockerfile -t ib-backend .
